

export enum ActionTypes {

  PRODUCT_SET = '[PRODUCT] PRODUCT_SET',
  PRODUCT_CLEAR = '[PRODUCT] PRODUCT_CLEAR',


  PRODUCTCATALOG_SET = '[PRODUCTCATALOG] PRODUCTCATALOG_SET',
  PRODUCTCATALOG_CLEAR = '[PRODUCTCATALOG] PRODUCTCATALOG_CLEAR',


  SHOPPINGCART_ADD = '[SHOPPINGCART] SHOPPINGCART_ADD',
  SHOPPINGCART_REMOVE = '[SHOPPINGCART] SHOPPINGCART_REMOVE',
  SHOPPINGCART_CLEAR = '[SHOPPINGCART] SHOPPINGCART_CLEAR',

  
  USER_LOGIN = '[USER] USER_LOGIN',
  USER_LOGOUT = '[USER] USER_LOGOUT',
  USER_AUTHENTICATED = '[USER] USER_AUTHENTICATED',

  USER_ORDERS_SET = '[USER_ORDER] USER_ORDERS_SET',
  USER_ORDERS_CLEAR = '[USER_ORDER] USER_ORDERS_CLEAR'


}